Repository pagopa/pagopa-anonymizer, pull requests merged in 2025-06, with the labels that each got.

#2 GitHub actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/release.yml
  .github/workflows/anchore.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/update_gha.py
  .gitignore
  setup.cfg
  sonar-project.properties
  test/__init__.py
  test/test_anonymizer.py
Labels: skip

#4 chore: Add quality gate to readme
  README.md
Labels: skip, size/small

#8 fix(Dockerfile): improve Dockerfile build and runtime configuration
  .gitignore
  Dockerfile
  src/anonymizer_logic.py
Labels: size/small

#10 feat: Openapi generation
  .github/workflows/code_review.yml
  .github/workflows/deploy_with_github_runner.yml
  .gitignore
  .identity/00_data.tf
  .identity/99_variables.tf
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/99_main.tf
  infra/99_variables.tf
  infra/api/v1/openapi.json
  infra/env/weu-dev/backend.ini
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/backend.ini
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/backend.ini
  infra/env/weu-uat/backend.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/policy/v1/_base_policy.xml.tpl
  infra/terraform.sh
  requirements.txt
  src/app.py
  test/test_app.py
  test/test_generate_openapi.py
Labels: size/large, skip

#11 fix: Deploy
  src/app.py
Labels: size/small, patch

#17 feat: [PAGOPA-3105] Define performance test
  .devops/performance-test-pipelines.yml
  README.md
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/anonymizer.js
  performance-test/src/env/dev.environment.json
  performance-test/src/env/local.environment.json
  performance-test/src/env/uat.environment.json
  performance-test/src/modules/anonymizer_client.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
Labels: size/large, skip
